// ============================================================
// FOUNDATIONS — single source of truth. Edit this file only.
// ============================================================
export const site = {
  name: "Foundations Business Development",
  shortName: "Foundations",
  tagline: "Build the base. Build the business.",
  domain: "foundationsdev.com",
  url: "https://foundationsdev.com",
  email: "troy@bdfoundations.com",
  phone: "(813) 402-8393",
  phoneRaw: "8134028393",
  region: "Tampa Bay",
  city: "Brandon",
  state: "FL",
  serviceAreas: ["Brandon", "Tampa", "Riverview", "Valrico", "Lithia", "Plant City", "Seffner"],
  hubspotPortalId: "246368131",
};

export const services = [
  { slug: "web-presence-builds", title: "Web Presence Builds", icon: "globe", addon: false, group: "Build & Own",
    tease: "Fast, owned sites that convert",
    image: "/images/svc-web.webp",
    blurb: "Fast, owned, conversion-built websites — not a rented page on someone else's platform.",
    intro: "Your website is the foundation everything else stands on. We build it on a clean, fast stack that loads in under a second, ranks in local search, and turns visitors into booked calls — and you own every piece of it.",
    points: [
      "Custom-built site on a fast static stack — no bloated templates",
      "You own the domain, the code, and every asset, forever",
      "Mobile-first design that looks sharp on every screen",
      "Built-in lead capture wired straight to your inbox or CRM",
      "Local SEO foundation baked in from day one",
      "No monthly platform fees, no holding your site hostage",
    ] },
  { slug: "google-business-profile", title: "Google Business Profile", icon: "pin", addon: false, group: "Get Found",
    tease: "Claimed, optimized, posting weekly",
    image: "/images/svc-gbp.webp",
    blurb: "The single highest-leverage local SEO move — claimed, optimized, and posting weekly.",
    intro: "For a local contractor, your Google Business Profile is often the first thing a homeowner sees — and most are half-built. We claim it, fully optimize it, and keep it active so you show up in the map pack when it counts.",
    points: [
      "Full claim and verification of your profile",
      "Complete optimization — categories, services, service areas, hours",
      "Professional photos and descriptions that build trust",
      "Weekly posts to keep your profile active and ranking",
      "Review monitoring so you never miss a customer",
      "The groundwork that gets you into Google's local map pack",
    ] },
  { slug: "local-seo", title: "Local SEO", icon: "search", addon: false, group: "Get Found",
    tease: "Rank in your service area",
    image: "/images/svc-seo.webp",
    blurb: "Service and area pages built to rank, so homeowners nearby find you first.",
    intro: "When a homeowner searches for what you do in your town, you want to be the first name they see. We build the page structure, content, and on-page signals local search rewards — so you get found by people ready to hire.",
    points: [
      "Dedicated service pages for everything you do",
      "Area pages targeting each town you serve",
      "Keyword research focused on real buyer searches",
      "On-page optimization — titles, meta, schema markup",
      "Google Search Console setup and monitoring",
      "Content that compounds in the rankings month over month",
    ] },
  { slug: "lead-generation-ads", title: "Lead Generation", icon: "target", addon: false, group: "Get Found",
    tease: "Meta & Google, no ad-spend markup",
    image: "/images/svc-leads.webp",
    blurb: "Meta & Google campaigns that put real leads in your pipeline — no markup on your ad spend.",
    intro: "When you need leads now, paid ads deliver. We build and run Meta and Google campaigns aimed at booked calls — not vanity clicks — and we never take a cut of your ad budget. You see exactly where every dollar goes.",
    points: [
      "Meta (Facebook & Instagram) lead campaigns",
      "Google Local Services and Search campaigns",
      "Ad creative and copy built to drive real inquiries",
      "Audience and location targeting dialed to your service area",
      "Zero markup on your ad spend — your budget is your budget",
      "Paired with speed-to-lead so no lead goes cold",
    ] },
  { slug: "speed-to-lead-automation", title: "Speed-to-Lead Automation", icon: "bolt", addon: false, group: "Convert & Grow",
    tease: "Auto-text every new lead in seconds",
    image: "/images/svc-speed.webp",
    blurb: "Every new lead gets an automatic text in seconds — before your competitor even sees them.",
    intro: "The contractor who responds first usually wins the job. The moment a lead comes in, an automated text fires on your behalf — so you're first in line every time, even when you're up on a roof or under a sink.",
    points: [
      "Instant automated SMS the second a lead comes in",
      "Keeps you first to respond — where most jobs are won",
      "Automatic email follow-up as a backup net",
      "Works around the clock, even after hours",
      "Every lead logged so nothing slips through the cracks",
      "Frees you to do the work without losing the next job",
    ] },
  { slug: "social-content", title: "Social Media & Content", icon: "image", addon: false, group: "Convert & Grow",
    tease: "Posts, custom images, full content library",
    image: "/images/svc-social.webp",
    blurb: "Consistent posts and custom branded images — drawn from our full content library.",
    intro: "An active, professional social presence tells homeowners you're the real deal. We keep your profiles posting consistently with custom branded images from our content library — so your feed always looks sharp without you touching it.",
    points: [
      "Consistent posting across your social platforms",
      "Custom branded images made for your business",
      "Full access to our professional content library",
      "Monthly content calendar planned for you",
      "Blog posts that feed your SEO and your feed",
      "Reels and short video on higher tiers",
    ] },
  { slug: "review-generation", title: "Review Generation", icon: "star", addon: false, group: "Convert & Grow",
    tease: "A steady stream of 5-star reviews",
    image: "/images/svc-reviews.webp",
    blurb: "A steady stream of real 5-star reviews — the trust signal that wins the click.",
    intro: "Reviews are the deciding factor for most homeowners. We build a simple system that asks your happy customers at exactly the right moment — so your star rating and review count keep climbing and keep winning you the next call.",
    points: [
      "Automated review requests timed to the job's finish",
      "Makes leaving a review effortless for your customers",
      "Steady growth in your star rating and review count",
      "Funnels happy customers to Google and Facebook",
      "Alerts so you can respond to every review",
      "The trust signal that wins the click over competitors",
    ] },
  { slug: "reputation-management", title: "Reputation Management", icon: "shield", addon: true, group: "Convert & Grow",
    tease: "Monitor reviews & mentions — add-on",
    image: "/images/svc-reputation.webp",
    blurb: "Stay on top of every review and mention across the web — your digital image, watched and managed.",
    intro: "Your reputation lives across dozens of sites. As an optional add-on, we monitor your reviews and mentions across platforms and help you manage them — so your digital image stays clean, current, and working for you.",
    points: [
      "Monitoring of reviews and mentions across platforms",
      "Alerts the moment something needs your attention",
      "Help crafting professional responses",
      "A consistent, trustworthy image everywhere you appear",
      "No added software fees — monitoring is handled for you",
      "Available as an add-on to any monthly plan",
    ] },
];

export const menuGroups = ["Build & Own", "Get Found", "Convert & Grow"];

export const buildTiers = [
  { name: "Footprint", price: "$750",
    desc: "A clean, fast one-page site built to get you found and capturing leads.",
    includes: [
      "Custom one-page website you own outright",
      "Mobile-first, loads in under a second",
      "Lead capture form wired to your inbox",
      "Click-to-call and click-to-text buttons",
      "Google Business Profile setup",
      "Basic local SEO — titles, meta, your core service & area",
      "SSL secured and launch-ready",
    ] },
  { name: "Blueprint", price: "$1,500", featured: true,
    desc: "A multi-page site with service and area pages — built to rank locally and convert.",
    includes: [
      "Everything in Footprint, plus:",
      "Multi-page website (home, services, about, contact)",
      "Dedicated service pages for what you do",
      "Area pages for the towns you serve",
      "Expanded local SEO foundation",
      "Photo gallery to show off your work",
      "Lead capture wired to your CRM",
      "Speed-to-lead automation ready to switch on",
    ] },
  { name: "Launchpad", price: "$2,500",
    desc: "The full presence: multi-page site, SEO foundation, and the back-office systems that compound.",
    includes: [
      "Everything in Blueprint, plus:",
      "Full brand guide — fonts, colors, voice, templates",
      "Email marketing setup — list + welcome sequence",
      "CRM setup — full lead pipeline (HubSpot)",
      "Estimate & invoice system setup (QuickBooks)",
      "Advanced SEO foundation + Search Console",
      "Full training workshop so you know your tools",
      "Priority support",
    ] },
];

// Rebrand path (shown as add-on options on pricing page)
export const rebrandOptions = [
  { name: "Brand Refresh", price: "$250", desc: "Polish what you have — refined logo treatment, color cleanup, and consistent fonts across your site and profiles." },
  { name: "Full Rebrand", price: "$1,200", desc: "Start fresh — new logo suite, complete brand guide, vehicle and signage templates, and a full website overhaul to match." },
];

export const monthlyPlans = [
  { name: "Signal", price: "$269", per:"/mo", tagline:"Stay found and active.",
    includes: [
      "Google Business Profile management",
      "Weekly GBP posts",
      "2 social posts / week",
      "Custom branded images from our content library",
      "Review generation system",
      "Monthly performance snapshot",
    ] },
  { name: "Momentum", price: "$369", per:"/mo", featured:true, tagline:"Build momentum every month.",
    inheritsFrom: "Signal",
    includes: [
      "3 social posts / week",
      "1 blog post / month",
      "Active local SEO work",
      "Content calendar",
      "Quarterly strategy check-in",
    ] },
  { name: "Builder", price: "$469", per:"/mo", tagline:"The full growth engine.",
    inheritsFrom: "Momentum",
    includes: [
      "4–5 social posts / week",
      "2 blog posts / month",
      "Monthly Reels / short video",
      "Priority support",
      "Expanded content library access",
    ] },
];

export const steps = [
  { n:"01", title:"We grade you", body:"Start with a free Web Presence Report Card — your site, profile, reviews, and SEO scored A–F across 8 dimensions." },
  { n:"02", title:"We build the base", body:"A fast, owned website and a fully optimized Google profile — the foundation everything else stands on." },
  { n:"03", title:"We compound it", body:"Reviews, content, and local SEO that keep working every month, so you get found and chosen over time." },
];

export const problems = [
  { pain:"My ad spend keeps climbing but the leads don't.",
    fix:"We run lead-focused campaigns with speed-to-lead automation, and we never mark up your ad spend — so every dollar works and every lead gets a text in seconds." },
  { pain:"I build like an A but show up online like a C.",
    fix:"We build the fast, owned web presence your reputation already earned — then keep it active with posts, reviews, and local SEO so homeowners actually find it." },
  { pain:"I'm renting my website and don't own a thing.",
    fix:"Everything we build is yours — domain, code, content, all of it. No platform hostage fees. Walk away anytime and it's still yours." },
];
